def generate_slr_template(title, pico_elements, studies):
    """
    Generate a structured SLR template based on PICO elements and included studies
    
    Args:
        title: The review title
        pico_elements: Dict containing Population, Intervention, Comparison, Outcome
        studies: List of included studies with their findings
    
    Returns:
        A structured SLR text
    """
    template = f"""# Systematic Literature Review: {title}

## PICO Framework
- **Population**: {pico_elements['population']}
- **Intervention**: {pico_elements['intervention']}
- **Comparison**: {pico_elements['comparison']}
- **Outcome**: {pico_elements['outcome']}

## Background
[Background text generated by the model based on PICO elements]

## Methods
### Search Strategy
[Search strategy details generated by model]

### Inclusion and Exclusion Criteria
[Criteria generated by model based on PICO]

### Study Selection
[Study selection process generated by model]

## Results
### Study Characteristics
[Summary of included studies]

### Primary Outcomes
[Analysis of primary outcomes across studies]

### Secondary Outcomes
[Analysis of secondary outcomes across studies]

## Discussion
[Discussion generated by model that synthesizes findings]

## Conclusion
[Conclusion that answers the research question]

## References
[List of references formatted according to standard citation guidelines]
"""
    return template